---
title: "Causal interpretation of the hazard ratio in RCTs"
author: "Dominic Magirr"
date: "2024-05-11"
categories: [Causal inference]
---

# Motivation

A new set of articles on the "Causal interpretation of the hazard ratio in randomized clinical trials" ( [original article](https://doi.org/10.1177/17407745241243308), [commentary](https://doi.org/10.1177/17407745241243307), [response](https://doi.org/10.1177/17407745241243311)) has pushed me to write this blogpost. It's something I've been considering for a while, not because it's the most important thing in the world, but there seems to be a persistent confusion, despite some [great attempts to clarify](https://thestatsgeek.com/2018/02/06/causal-interpretation-of-the-hazard-ratio-from-rcts-when-proportional-hazards-holds/)

# Source of the confusion

The mistake (in my eyes) is to claim something like "the hazard ratio is not a causal effect" (in the context of an RCT) without first providing a precise definition of "causal effect".

# Definition A

One clean and precise definition of a causal effect is provided by Hernan & Robins [Technical Point 1.1](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)...

*In general, a population causal effect can be defined as a contrast of any functional of the marginal distributions of counterfactual outcomes under different actions or treatment values.*

The hazard ratio, $hr(t)$, satisfies this definition, for any choice of $t$. Therefore, if we follow this definition, then the hazard ratio is a causal effect. End of story. We can all move on.

# Criticism of hazard ratios in loose language

["The hazards of hazard ratios" (Hernan, 2010)](https://journals.lww.com/epidem/fulltext/2010/01000/The_Hazards_of_Hazard_Ratios.4.aspx?trk=public_post_comment-text) contains an example where the hazard ratio (hormone therapy vs control) after 5 years is less than 1 "even if hormone therapy has no truly preventive effect in any woman at any time."

Interestingly, though, the fact that a hazard ratio can ostensibly point in favour of an experimental treatment despite no true benefit is not the grounds given for claiming that a hazard ratio lacks a causal interpretation. For example, the so-called ["total effect" in a competing risks setting](https://doi.org/10.1002/sim.8471) also has the property that it can be less than 1 (if it's a ratio) despite no true benefit. Yet this is unequivocally a causal effect according to the authors.

Rather, the grounds given for claiming the hazard ratio is not a causal effect is always given in loose language, e.g., it somehow does not compare equal groups, or has a so-called ["in-built selection bias"](https://academic.oup.com/eurheartj/advance-article-pdf/doi/10.1093/eurheartj/ehy770/46637053/ehy770.pdf?casa_token=epq6jgF2ZvIAAAAA:Uw86S5iQCVUvjikBaIHN-Gtcax9zYFOkThX6ZvnnhBNwh2Slduhy9xrZ5FYB9qSYjVuANL8Hc_dLUQ). This is ambiguous. I would say that a hazard ratio at 5 years is a consequence of everything that happens to everyone in the first 5 years. It is not merely a comparison of the set of patients alive at 5 years, as if the patients who have died had never existed.

# Definition B

I've not seen a precise definition of a causal effect that would rule out the hazard ratio, so I'll make one up here...

*In general, a population causal effect can be defined as a contrast of any functional **(except for a conditional expectation where the conditioning is on a post-baseline event)** of the marginal distributions of counterfactual outcomes under different actions or treatment values.*

If we follow this definition, then the hazard ratio is not (in general) a causal effect. End of story. We can all move on.

The reason for "in general" is that if the hazard ratio happens to be constant over time then it coincides with the difference in survival curves on the complimentary log log scale, which is an unconditional expectation.

# Which definition is better?

Given that both the hazard ratio and total effect have the same property that they can be less than 1 despite no true benefit, I prefer Definition A to Definition B.

Both the hazard ratio and the total effect require deep thought to understand. Neither has a straightforward interpretation. To use definition B, and therefore make the distinction that the total effect is causal and the hazard ratio in not causal, is a pure technicality in my eyes.
