project:
  type: website
  output-dir: docs

website:
  title: "Dominic Magirr"
  site-url: https://dominicmagirr.github.io/blog/
  description: "A blog about statistical methodology in clinical trials"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dominicmagirr
      - icon: twitter
        href: https://twitter.com/DominicMagirr
      - icon: linkedin
        href: https://uk.linkedin.com/in/dominic-magirr-87666b12b
      - icon: google
        href: https://scholar.google.co.uk/citations?user=obri2xMAAAAJ&hl=en
      - icon: youtube
        href: https://www.youtube.com/@dominicmagirr5571
      - icon: rss
        href: index.xml
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

comments:
  giscus:
    repo: dominicmagirr/blog
